### ISSUE TITLE
QR code is not valid by some scanners

### ISSUE THREAD

**Issue by BenBeri** [kozakdenys/qr-code-styling#105] opened 2022-01-05 14:35 UTC
I have used the example code of facebook looking QR code from the README, I scanned it with my iphone and it worked, however with all andorid phones I've used it could not get the data, I used this online scanner https://pageloot.com/qr-code-scanner and it could not detect it aswell. I used some online QR code generator, scanned it with all phones and it worked everywhere.

I used the Angular example.

Is there an known issue about this?

**Comment by Stedioz** [comment] 2022-01-28 10:19
I confirm, android scanners do not recognize the generated qr code.

**Comment by jaqarrick** [comment] 2022-05-09 23:39
@Stedioz @BenBeri 👋 Hi there! Wondering if you are still experiencing issues scanning with Android devices. I tested with an Android device and it seemed to work fine. This was using the React example with the built in scanner on my device. Thanks in advance!

**Comment by brianpmaher** [comment] 2022-07-20 19:07
Any suggestion on qr scanner packages that do work well with these?

**Comment by jaqarrick** [comment] 2022-07-21 16:49
Still no issues with this library and android (and other devices).. I'm wondering how much these inconsistencies have to do with QR functionality itself, meaning that QR codes become less usable / reliable the more styles and adjustments are added. [Here are some other reasons a QR code might not work](https://www.qrcode-tiger.com/qr-code-not-working).

**Comment by victorbianconi** [comment] 2022-07-29 21:32
Seems to be an issue with images from my side, and non-square dots. Any idea how we can use images and still get it working?

**Comment by KilianB** [comment] 2022-08-26 13:36
Probably duplicate of #49

**Comment by KilianB** [comment] 2022-08-27 12:17
@victorbianconi and @Stedioz  can you please check if the below codes are working on your android devices?

The top row are fixed codes and the bottom row are codes generated with this library. I got an npm package release almost ready, just need to write the changelogs and publish it tomorrow.

![image](https://user-images.githubusercontent.com/9025925/187029849-066d3016-234c-4a25-9bd1-9925023c8722.png)

**Comment by victorbianconi** [comment] 2022-08-28 21:17
> @victorbianconi and @Stedioz can you please check if the below codes are working on your android devices?
> 
> The top row are fixed codes and the bottom row are codes generated with this library. I got an npm package release almost ready, just need to write the changelogs and publish it tomorrow.
> 
> ![image](https://user-images.githubusercontent.com/9025925/187029951-4c870d54-5ea4-4e36-9679-e7b46122cc64.png)
> 
> The package can now be installed via `npm i styled-qr-code` or `yarn add styled-qr-code`
> 
> https://github.com/KilianB/styled-qr-code

The purple one works for me. I'm using the android's scanner app. But the other ones don't work. I figured out it likely has to do with low contrast colors/background color.

**Comment by madmacc** [comment] 2022-09-19 22:22
I just discovered the same issue and I have this in a production app. Works fine for ios but the Android native camera for all the devices we tested does not work. Google Lens works but that is not available by default for older devices.

Note: Url points to https://cat-bounce.com/

**Created with qr-code-styling (does not work)**
![qr-code-styling-margin-30](https://user-images.githubusercontent.com/43654472/191129865-c56f3214-73fc-46e2-bb08-f7d844741312.png)

**Created with qr-code-generator (works fine)**
![qr-code-generator](https://user-images.githubusercontent.com/43654472/191129881-f69fd565-7d48-496b-a0d9-9a963b8f894d.png)

I will test the QR codes above and check out the new package.

**Comment by madmacc** [comment] 2022-09-19 23:21
> @victorbianconi and @Stedioz can you please check if the below codes are working on your android devices?
> 
> The top row are fixed codes and the bottom row are codes generated with this library. I got an npm package release almost ready, just need to write the changelogs and publish it tomorrow.
> 
> ![image](https://user-images.githubusercontent.com/9025925/187029951-4c870d54-5ea4-4e36-9679-e7b46122cc64.png)
> 
> The package can now be installed via `npm i styled-qr-code` or `yarn add styled-qr-code`
> 
> https://github.com/KilianB/styled-qr-code

The bottom row seems to work but inconsistently, may be the contrast. I will try your fork with a plain square black QR code and see how it goes.

**Comment by smappio** [comment] 2022-10-04 09:25
> I just discovered the same issue and I have this in a production app. Works fine for ios but the Android native camera for all the devices we tested does not work. Google Lens works but that is not available by default for older devices.
> 
> Note: Url points to https://cat-bounce.com/
> 
> **Created with qr-code-styling (does not work)** ![qr-code-styling-margin-30](https://user-images.githubusercontent.com/43654472/191129865-c56f3214-73fc-46e2-bb08-f7d844741312.png)
> 
> **Created with qr-code-generator (works fine)** ![qr-code-generator](https://user-images.githubusercontent.com/43654472/191129881-f69fd565-7d48-496b-a0d9-9a963b8f894d.png)
> 
> I will test the QR codes above and check out the new package.

Both QRcodes work for me and my Android Oppo.

**Comment by madmacc** [comment] 2022-10-06 20:13
@smappio It appears to only be an issue for Android 8 and possibly earlier.
See https://github.com/kozakdenys/qr-code-styling/pull/110 and https://github.com/kozakdenys/qr-code-styling/issues/49

**Comment by smappio** [comment] 2022-10-06 20:24
Yeah, I understand. I've restricted the colors on my side, so that I prevent any lack of contrast and at the moment, no more issue with guys scanning my users ' qrcode. Fyi I restrict colors to the 700/800/900 variants of tailwindcss colors.

**Comment by smappio** [comment] 2022-10-06 20:26
You can try if you want, connect lechapeau.io, create your account (you can delete it after), go to the qrcode tab of your user profile (your "Chapeau" created at sign up). I'd be interested to know if some colors settings are not working with the color restriction and for some devices.

**Comment by madmacc** [comment] 2022-10-06 20:32
At the moment I am using @HenkVanMaanen's fork https://github.com/sallandpioneers/qr-code-styling and it works well as long as you don't use the rounded dots.
The issues I am concerned about are not related to colours but with a bug in the code generating the QR code.

**Comment by smappio** [comment] 2022-10-06 20:51
Oh ok, sorry. I use the original version on my ends.

**Closed** 2024-10-14 12:25 UTC

**Comment by kozakdenys** [comment] 2024-10-23 13:13
Hi @BenBeri @brianpmaher @KilianB @jaqarrick @madmacc @victorbianconi @smappio @Stedioz, sorry for leaving you for so long

The fix was released in version [v1.7.1](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.7.1) and above.
