### ISSUE TITLE
not rendering correctly

### ISSUE THREAD

**Issue by farahats9** [kozakdenys/qr-code-styling#80] opened 2021-09-16 13:06 UTC
When creating 2 QR codes in the same page, the image is completely black in the 2nd rendered one. I have done some digging and found that the problem is that the rects are using the same id for clip-path `#clip-path-dot-color` here

https://github.com/kozakdenys/qr-code-styling/blob/2e3d6b366f35eb3535f80ed4ef1540ffbca4343d/src/core/QRSVG.ts#L420

https://github.com/kozakdenys/qr-code-styling/blob/2e3d6b366f35eb3535f80ed4ef1540ffbca4343d/src/core/QRSVG.ts#L174

It needs to be changed to be different with each new QR code created or find another way to draw it without using an id if possible, I am not experienced enough with svg to do it.

**Comment by chulapitta** [comment] 2022-03-10 15:13
This bug results in multiple QR generated having the same duplicated code-image if using SVG mode. You can use canvas mode instead when generating multiple QRs.

**Comment by vicnoob** [comment] 2022-10-04 08:48
@chulapitta So that mean if I have multi QR code I must use Canvas mode, no other choices?

**Comment by kozakdenys** [comment] 2024-10-22 12:30
Hi @farahats9 @TommyCardello @chulapitta @vicnoob , sorry for my late response, it seems like a duplicate of https://github.com/kozakdenys/qr-code-styling/issues/210

**Closed by kozakdenys** 2024-10-22 12:30 UTC
