### ISSUE TITLE
Multiples downloads dont work

### ISSUE THREAD

**Issue by JoaquinDecima** [kozakdenys/qr-code-styling#84] opened 2021-10-14 14:50 UTC
First of all I apologize for my English, it is really bad.

When Downloading a QR (Angular) and generating a new one without updating the component, the download returns to the old QR.

I am working on a site that makes QRs for which I need that after downloading a QR I can generate another without refreshing the WEB. The problem is that when I generate the second one I download the first one again. I think the error is here but I'm really not sure

```js
export default function downloadURI(uri: string, name: string): void {
  const link = document.createElement("a");
  link.download = name;
  link.href = uri;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
```

The download works on the same file it should always be destroyed after downloading or they should be different.

**Comment by JosephShepin** [comment] 2022-03-28 04:07
experiencing same issue

**Comment by JosephShepin** [comment] 2022-03-28 04:17
I had the same issue. As of right now, [1.5.0](https://www.npmjs.com/package/qr-code-styling/v/1.5.0) works without the issue. Anything past that and the downloaded QR code doesn't update.

**Comment by xunorus** [comment] 2022-11-17 04:01
I cant make multiples QR to work even at current 1.5.0 version. 
(https://unpkg.com/qr-code-styling@1.5.0/lib/qr-code-styling.js )

For example this code gives me the same QR image .:
```
let q1 = new QRCodeStyling({ width: 300, height: 300, type: "png", data: 'uno', image: `yourlogo.jpg`, 
      dotsOptions: { color: "#1568B0", type: "extra-rounded" }, 
      backgroundOptions: { color: "#fff", }, 
      imageOptions: { crossOrigin: "anonymous", margin: 0 } });


let q2 = new QRCodeStyling({ width: 300, height: 300, type: "png", data: 'dos', image: `yourlogo.jpg`, 
      dotsOptions: { color: "#1568B0", type: "extra-rounded" }, 
      backgroundOptions: { color: "#fff", }, 
      imageOptions: { crossOrigin: "anonymous", margin: 0 } });


q1.append(document.getElementById('qr'+1));
q2.append(document.getElementById('qr'+2));

```

Any ideas?

**Comment by xunorus** [comment] 2022-11-17 16:54
I manage to use it with getRawData method: 

HTML:
```
<img id="qr1" src=""/>
<img id="qr2" src=""/>
```
JS
```
 document.getElementById('qr1').src =  URL.createObjectURL(await q1.getRawData('png'))
 document.getElementById('qr2').src =  URL.createObjectURL(await q2.getRawData('png'))
```

**Comment by kozakdenys** [comment] 2024-10-22 11:37
Hi @xunorus @JoaquinDecima @JosephShepin , it seems like a duplicate of https://github.com/kozakdenys/qr-code-styling/issues/210

**Closed by kozakdenys** 2024-10-22 11:37 UTC

**Comment by chrisspiegl** [comment] 2025-02-21 17:47
I ran into the same issue and was only able to solve it by destorying and then recreating the `new QRCodeStyling(options.value)`. 
All other options lead to the same image being downloaded again and again.
I wonder what's going on there.
