### ISSUE TITLE
Margin Value is ignored

### ISSUE THREAD

**Issue by Damian710** [kozakdenys/qr-code-styling#97] opened 2021-11-24 17:51 UTC
Setting margin to '0' doesn't remove the margin from the qr-code. I can set a negative value to margin, but its getting ignored unless a specific negative value (depending on the given height and width values)

The QR is shown with margin with these given values

  margin: -9,
  height: 176,
  width: 176,
  
<img width="231" alt="Bildschirmfoto 2021-11-24 um 18 53 48" src="https://user-images.githubusercontent.com/45567428/143290526-aff1a71d-3598-4d41-9311-6b24860228bb.png">

  
if I change the margin to '-10' the margin is removed but so much that the qr gets cut off a little bit
  

<img width="239" alt="Bildschirmfoto 2021-11-24 um 18 53 00" src="https://user-images.githubusercontent.com/45567428/143290500-6a91ed1f-706d-4950-a3dc-df28239b841b.png">

**Comment by chiptu** [comment] 2021-11-25 23:17
Strange on vuejs 3 i don't have this issue
![Capture d’écran 2021-11-26 à 00 15 40](https://user-images.githubusercontent.com/35498845/143506992-e135ab99-f112-40b8-a85a-6270ca982752.png)

**Comment by marat-ad** [comment] 2021-12-03 23:10
@Damian710 This is happening due to this code:
```typescript
const dotSize = Math.floor(realQRSize / count);
const xBeginning = Math.floor((options.width - count * dotSize) / 2);
const yBeginning = Math.floor((options.height - count * dotSize) / 2);
```
where `xBeginning` and `yBeginning` are the pixel numbers on the background where dots drawing will start.
When width and height are small but encoded text is long it will lead to unexpected results.

Say we have width: 100, height: 100, and long text that produces 40 dots in qr code per line. According to the code above we will get:
```
dotSize = Math.floor(100 / 40) = 2
xBeginning = Math.floor((100 - 40 * 2) / 2) = 10
yBeginning = Math.floor((100 - 40 * 2) / 2) = 10
```
That means we will get 10px padding.

I believe this is done for the canvas support. If we remove `Math.floor` calls and use float values, it will draw dots starting from 0px as expected, but dot width will be 2.5px. That works good with svg, but on canvas image gets blurry.

**Comment by stevefai** [comment] 2024-01-17 14:06
Please see my comment: https://github.com/kozakdenys/qr-code-styling/issues/104#issuecomment-1895874708

**Comment by kozakdenys** [comment] 2024-10-20 18:40
Duplicate of #104.
You can use `dotOptions.roundSize = false` now.
More details in [comment](https://github.com/kozakdenys/qr-code-styling/issues/104#issuecomment-1771854501) and [comment](https://github.com/kozakdenys/qr-code-styling/issues/104#issuecomment-2425170881)

**Closed by kozakdenys** 2024-10-20 18:40 UTC
Labels: duplicate
