### ISSUE TITLE
Margin not working properly

### ISSUE THREAD

**Issue by Psycarlo** [kozakdenys/qr-code-styling#209] opened 2024-07-11 00:02 UTC
Reproduce steps:

1. https://qr-code-styling.com/
2. Width: 200
3. Height: 200
4. Change margin one by one

It only changes around every 10-15 points.

**Comment by Psycarlo** [comment] 2024-07-12 19:33
Maybe we could remove margin entirely so users can handle that on a outside div? So the canvas would always present the the qrcode with no margin, which means all outer points touching the border.

**Comment by kozakdenys** [comment] 2024-10-20 18:43
Hi @Psycarlo,
It looks like a duplicate of https://github.com/kozakdenys/qr-code-styling/issues/104.
You can use dotOptions.roundSize = false now.
More details in https://github.com/kozakdenys/qr-code-styling/issues/104#issuecomment-1771854501 and https://github.com/kozakdenys/qr-code-styling/issues/104#issuecomment-2425170881

**Closed by kozakdenys** 2024-10-20 18:43 UTC
Labels: duplicate
